ALTER TABLE player
ADD COLUMN preseason_ranking INTEGER;

UPDATE player SET preseason_ranking = 1 WHERE player_name = 'aspas' AND team_abrev = 'LEV';
UPDATE player SET preseason_ranking = 2 WHERE player_name = 'jawgemo' AND team_abrev = 'EG';
UPDATE player SET preseason_ranking = 3 WHERE player_name = 'Victor' AND team_abrev = 'NRG';
UPDATE player SET preseason_ranking = 4 WHERE player_name = 'keznit' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 5 WHERE player_name = 'zekken' AND team_abrev = 'SEN';
UPDATE player SET preseason_ranking = 6 WHERE player_name = 'eeiu' AND team_abrev = '100T';
UPDATE player SET preseason_ranking = 7 WHERE player_name = 's0m' AND team_abrev = 'NRG';
UPDATE player SET preseason_ranking = 8 WHERE player_name = 'OXY' AND team_abrev = 'C9';
UPDATE player SET preseason_ranking = 9 WHERE player_name = 'leaf' AND team_abrev = 'G2';
UPDATE player SET preseason_ranking = 10 WHERE player_name = 'Khalil' AND team_abrev = 'FUR';
UPDATE player SET preseason_ranking = 11 WHERE player_name = 'kiNgg' AND team_abrev = 'LEV';
UPDATE player SET preseason_ranking = 12 WHERE player_name = 'cauanzin' AND team_abrev = 'LOUD';
UPDATE player SET preseason_ranking = 13 WHERE player_name = 'Cryocells' AND team_abrev = '100T';
UPDATE player SET preseason_ranking = 14 WHERE player_name = 'TenZ' AND team_abrev = 'SEN';
UPDATE player SET preseason_ranking = 15 WHERE player_name = 'mwzera' AND team_abrev = 'FUR';
UPDATE player SET preseason_ranking = 16 WHERE player_name = 'Asuna' AND team_abrev = '100T';
UPDATE player SET preseason_ranking = 17 WHERE player_name = 'Ethan' AND team_abrev = 'NRG';
UPDATE player SET preseason_ranking = 18 WHERE player_name = 'Palla' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 19 WHERE player_name = 'Derrek' AND team_abrev = 'EG';
UPDATE player SET preseason_ranking = 20 WHERE player_name = 'tuyz' AND team_abrev = 'LOUD';
UPDATE player SET preseason_ranking = 21 WHERE player_name = 'Mazino' AND team_abrev = 'LEV';
UPDATE player SET preseason_ranking = 22 WHERE player_name = 'heat' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 23 WHERE player_name = 'Less' AND team_abrev = 'LOUD';
UPDATE player SET preseason_ranking = 24 WHERE player_name = 'bang' AND team_abrev = '100T';
UPDATE player SET preseason_ranking = 25 WHERE player_name = 'valyn' AND team_abrev = 'G2';
UPDATE player SET preseason_ranking = 26 WHERE player_name = 'Xeppaa' AND team_abrev = 'C9';
UPDATE player SET preseason_ranking = 27 WHERE player_name = 'JonahP' AND team_abrev = 'G2';
UPDATE player SET preseason_ranking = 28 WHERE player_name = 'pANcada' AND team_abrev = 'LOUD';
UPDATE player SET preseason_ranking = 29 WHERE player_name = 'supamen' AND team_abrev = 'EG';
UPDATE player SET preseason_ranking = 30 WHERE player_name = 'Melser' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 31 WHERE player_name = 'artzin' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 32 WHERE player_name = 'havoc' AND team_abrev = 'FUR';
UPDATE player SET preseason_ranking = 33 WHERE player_name = 'trent' AND team_abrev = 'G2';
UPDATE player SET preseason_ranking = 34 WHERE player_name = 'crashies' AND team_abrev = 'NRG';
UPDATE player SET preseason_ranking = 35 WHERE player_name = 'saadhak' AND team_abrev = 'LOUD';
UPDATE player SET preseason_ranking = 36 WHERE player_name = 'tex' AND team_abrev = 'LEV';
UPDATE player SET preseason_ranking = 37 WHERE player_name = 'nzr' AND team_abrev = 'FUR';
UPDATE player SET preseason_ranking = 38 WHERE player_name = 'Shyy' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 39 WHERE player_name = 'icy' AND team_abrev = 'G2';
UPDATE player SET preseason_ranking = 40 WHERE player_name = 'Sacy' AND team_abrev = 'SEN';
UPDATE player SET preseason_ranking = 41 WHERE player_name = 'Boostio' AND team_abrev = '100T';
UPDATE player SET preseason_ranking = 42 WHERE player_name = 'NaturE' AND team_abrev = 'EG';
UPDATE player SET preseason_ranking = 43 WHERE player_name = 'Zellsis' AND team_abrev = 'SEN';
UPDATE player SET preseason_ranking = 44 WHERE player_name = 'C0M' AND team_abrev = 'LEV';
UPDATE player SET preseason_ranking = 45 WHERE player_name = 'moose' AND team_abrev = 'C9';
UPDATE player SET preseason_ranking = 46 WHERE player_name = 'johnqt' AND team_abrev = 'SEN';
UPDATE player SET preseason_ranking = 47 WHERE player_name = 'mazin' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 48 WHERE player_name = 'runi' AND team_abrev = 'C9';
UPDATE player SET preseason_ranking = 49 WHERE player_name = 'Apoth' AND team_abrev = 'EG';
UPDATE player SET preseason_ranking = 50 WHERE player_name = 'rich' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 51 WHERE player_name = 'vanity' AND team_abrev = 'C9';
UPDATE player SET preseason_ranking = 52 WHERE player_name = 'FiNESSE' AND team_abrev = 'NRG';
UPDATE player SET preseason_ranking = 53 WHERE player_name = 'xand' AND team_abrev = 'FUR';
UPDATE player SET preseason_ranking = 54 WHERE player_name = 'liazzi' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 55 WHERE player_name = 'mta' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 56 WHERE player_name = 'ShahZaM' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 57 WHERE player_name = 'Pa1nt' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 58 WHERE player_name = 'Klaus' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 59 WHERE player_name = 'Blaze' AND team_abrev = '100T';
UPDATE player SET preseason_ranking = 60 WHERE player_name = 'Phantom' AND team_abrev = 'EG';
UPDATE player SET preseason_ranking = 61 WHERE player_name = 'Vortex' AND team_abrev = 'NRG';
UPDATE player SET preseason_ranking = 62 WHERE player_name = 'Shadow' AND team_abrev = 'SEN';
UPDATE player SET preseason_ranking = 63 WHERE player_name = 'Ghost' AND team_abrev = 'KRU';
UPDATE player SET preseason_ranking = 64 WHERE player_name = 'Stone' AND team_abrev = 'MIBR';
UPDATE player SET preseason_ranking = 65 WHERE player_name = 'Ironclad' AND team_abrev = 'C9';
UPDATE player SET preseason_ranking = 66 WHERE player_name = 'Fortress' AND team_abrev = 'LEV';
UPDATE player SET preseason_ranking = 67 WHERE player_name = 'Bulwark' AND team_abrev = 'FUR';
UPDATE player SET preseason_ranking = 68 WHERE player_name = 'Sentinel' AND team_abrev = 'LOUD';



SELECT * FROM player;